version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
  app:
    build: .
    ports:
      - "3000:3000" # Mapping host port 3000 to container port 3000
    environment:
      MONGOUSER: root
      MONGOPASS: password
      MONGOHOST: mongo
      MONGOPORT: 27017
      MONGONAME: 'MongoDB Database'
      PORT: 3000
    depends_on:
      - mongo

volumes:
  mongo-data:
